# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-07 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0003_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='connected_to',
            field=models.ManyToManyField(related_name='_section_connected_to_+', to='sql_web.Section'),
        ),
    ]
