# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0007_auto_20160211_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='connected_to',
            field=models.ManyToManyField(blank=True, to='sql_web.Section'),
        ),
    ]
