# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0008_auto_20160211_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='example',
            name='programming_language',
        ),
        migrations.AddField(
            model_name='example',
            name='language',
            field=models.CharField(choices=[('lang-sql', 'SQL'), ('lang-php', 'PHP')], default='lang-sql', max_length=20),
        ),
    ]
