# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0009_auto_20160218_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='section',
        ),
    ]
