# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0010_remove_exercise_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='prepopulated',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
