# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0011_exercise_prepopulated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='given_schema',
            field=models.TextField(blank=True),
        ),
    ]
