# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 21:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sql_web', '0012_auto_20160219_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('assigned_to', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('exercises', models.ManyToManyField(to='sql_web.Exercise')),
                ('reading', models.ManyToManyField(to='sql_web.Section')),
            ],
        ),
    ]
