# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-03 21:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0013_assignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assigned_to',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='exercises',
            field=models.ManyToManyField(blank=True, to='sql_web.Exercise'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='reading',
            field=models.ManyToManyField(blank=True, to='sql_web.Section'),
        ),
    ]
