# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-11 12:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0016_auto_20160309_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='read_by',
            field=models.ManyToManyField(blank=True, related_name='read', to=settings.AUTH_USER_MODEL),
        ),
    ]
