# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-04 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0017_auto_20160311_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='rendered_contents',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
