# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0019_footnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='contents',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
