# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 10:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0020_section_contents'),
    ]

    operations = [
        migrations.RenameField(
            model_name='footnote',
            old_name='raw_contents',
            new_name='contents',
        ),
        migrations.RemoveField(
            model_name='footnote',
            name='rendered_contents',
        ),
        migrations.RemoveField(
            model_name='footnote',
            name='section',
        ),
    ]
