# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-26 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0021_auto_20160526_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='footnote',
            name='section',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='sql_web.Section'),
            preserve_default=False,
        ),
    ]
