# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 11:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0023_remove_figure_short_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='figure',
            old_name='full_description',
            new_name='description',
        ),
    ]
