# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-30 15:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0024_auto_20160530_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='html_contents',
        ),
    ]
