# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-06 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0025_remove_section_html_contents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('subject__number', 'title')},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('number',)},
        ),
        migrations.AddField(
            model_name='subject',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='example',
            name='language',
            field=models.CharField(choices=[('lang-sql', 'SQL'), ('lang-php', 'PHP'), ('lang-python', 'Python'), ('lang-java', 'Java')], default='lang-sql', max_length=20),
        ),
    ]
