# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-26 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0027_auto_20160606_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('contents', models.TextField()),
                ('rendered_contents', models.TextField()),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.AlterField(
            model_name='example',
            name='language',
            field=models.CharField(choices=[('lang-sql', 'SQL'), ('lang-php', 'PHP'), ('lang-python', 'Python'), ('lang-java', 'Java'), ('lang-bash', 'Bash')], default='lang-sql', max_length=20),
        ),
    ]
