# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-04 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sql_web', '0033_auto_20160803_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='completed_by',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
