# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-04 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0034_exercise_completed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='associated_exercises',
            field=models.ManyToManyField(blank=True, to='sql_web.Exercise'),
        ),
    ]
