# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-08 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0036_exercise_statement_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='rendered_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='prepopulated',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='statement_type',
            field=models.CharField(choices=[('DDL', 'Other'), ('DML', 'SELECT')], default='DML', max_length=3),
        ),
    ]
