# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-11 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0037_auto_20160808_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='visible',
            field=models.BooleanField(default=True, help_text='Fjarlægið hakið til að fela efnið frá nemendum.'),
        ),
    ]
