# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-12 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0039_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='good_start',
            field=models.BooleanField(default=False, help_text='Merkja má við hér til að benda nemendum á að lesa þessa grein snemma.'),
        ),
    ]
