# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-16 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0041_auto_20160812_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ('subject__number', 'distance', 'title')},
        ),
        migrations.AddField(
            model_name='section',
            name='distance',
            field=models.IntegerField(default=0, help_text='Reiknuð fjarlægð frá ráðlagðri upphafsgrein viðfangsefnisins'),
        ),
    ]
