# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-16 12:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0042_auto_20160816_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='best_start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='considered_best_start_by', to='sql_web.Section'),
        ),
    ]
