# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-18 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0043_auto_20160816_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assignment',
            old_name='assigned_to',
            new_name='assigned_students',
        ),
        migrations.AddField(
            model_name='assignment',
            name='assigned_course',
            field=models.ManyToManyField(blank=True, help_text='Setja verkefni fyrir alla nemendur í námskeiðinu', to='sql_web.Course'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
