# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-21 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_web', '0045_auto_20160903_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='visible',
            field=models.BooleanField(default=True, help_text='Breytið til að fela eða sýna allar tengdar greinar'),
        ),
    ]
